#!/usr/bin/env perl
use strict;
use warnings;
use 5.010;

use Encode;

use YAML::PP::Common;
use YAML::PP::Parser;

my $parser = YAML::PP::Parser->new(
  receiver => sub {
    my ($self, @args) = @_;
    my $event;
    if (@args == 1) {
        $event = YAML::PP::Common::event_to_test_suite($args[0]);
    }
    else {
        $event = YAML::PP::Common::event_to_test_suite($args[1]);
    }
    $event = encode_utf8($event);
    say $event;
  },
);

my $yaml = decode_utf8 do { local $/; <> };
$parser->parse_string($yaml);
